name: Build and Push Container Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    permissions:
      contents: read
      packages: write

    runs-on: ubuntu-22.04

    steps:
      - name: Configure QEMU
        uses: docker/setup-qemu-action@v2

      - name: Configure Docker
        uses: docker/setup-buildx-action@v2

      - name: Login to Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: secretfader
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Docker Metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          tags: latest,2023.02

      - name: Build and Push Container Image
        uses: docker/build-push-action@v4
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
